language: groovy 
jdk:
# commented Java8 untill compatibility is fixed
#  - oraclejdk8
  - oraclejdk7
  - openjdk7

env: TERM=dumb

install: ./gradlew clean -u- -i npmInstall

script: ./gradlew clean -u -i -S test

## after_success: ./gradlew coveralls
