version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - SET PATH=%JAVA_HOME%\bin;
  - echo %PATH%
  - gradlew.bat clean npmInstall
build_script:
  - gradlew.bat -u -i build
test_script:
  - gradlew.bat -u -i -S test
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
on_failure:
  - echo It seems something went kaput